profile/urls.py
from django.urls import path

from .views import Login, Logout, Profile, Register

urlpatterns = [
    path('', Profile.as_view(), name='profile'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from mainpage.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('tasks/', include('tasks.urls')),
    path('profile/', include('profile.urls')),
]

tasks/urls.py
from django.urls import path

from .views import TaskListView, CreateTaskView, DeleteTaskView, UpdateTaskView

urlpatterns = [
    path('', TaskListView.as_view(), name='tasks'),
    path('create/', CreateTaskView.as_view(), name='create_task'),
    path('delete/<int:pk>', DeleteTaskView.as_view(), name='delete_task'),
    path('update/<int:pk>', UpdateTaskView.as_view(), name='update_task'),
]

mainpage/models.py
from django.db import models

# Create your models here.

profile/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.conf.global_settings import AUTH_USER_MODEL
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)

profile/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}), label='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}), label='')


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=25, required=True, widget=forms.TextInput(attrs={'placeholder': 'username'}), label='')
    email = forms.CharField(max_length=50, required=True, widget=forms.EmailInput(attrs={'placeholder': 'email'}), label='')
    password1 = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput(attrs={'placeholder': 'password'}), label='')
    password2 = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput(attrs={'placeholder': 'confirm password'}), label='')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

tasks/forms.py
from django import forms

from tasks.models import Task


class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}), max_length=25, required=True, label='')

    class Meta:
        model = Task
        fields = ['title']

mainpage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'mainpage/index.html', {'request': request})

profile/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, TemplateView
from django.shortcuts import redirect, render
from django.views.generic import CreateView

from profile.forms import LoginForm, RegisterForm


class Login(LoginView):
    form_class = LoginForm
    template_name = 'profile/login.html'
    redirect_authenticated_user = True


class Logout(LogoutView):
    next_page = 'login'


class Register(CreateView):
    template_name = 'profile/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account was created successfully')
            return redirect(to='login')
        return render(request, self.template_name, {'form': form})


class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'profile/index.html'

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from tasks.forms import TaskForm
from tasks.models import Task


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'tasks/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = context['object_list'].filter(author=self.request.user).order_by('-created_at')
        return context


class CreateTaskView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'tasks/modals/create_task_modal.html'
    form_class = TaskForm

    def get(self, request, *args, **kwargs):
        if not is_ajax(request):
            return redirect('tasks')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.author = request.user
            form_instance.save()
            return redirect('tasks')
        return render(request, self.template_name, {'form': form})


class DeleteTaskView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('tasks')
    template_name = 'tasks/modals/delete_task_modal.html'

    def get(self, request, *args, **kwargs):
        if not is_ajax(request):
            return redirect('tasks')
        return super().get(request, *args, **kwargs)


class UpdateTaskView(LoginRequiredMixin, UpdateView):
    model = Task
    success_url = reverse_lazy('tasks')
    template_name = 'tasks/modals/update_task_modal.html'
    form_class = TaskForm

    def get(self, request, *args, **kwargs):
        if not is_ajax(request):
            return redirect('tasks')
        return super().get(request, *args, **kwargs)


def is_ajax(request):
    return request.headers.get('x-requested-with') == 'XMLHttpRequest'

mainpage/templates/mainpage/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="description row justify-content-center text-center">
    <h3>Django learning web project. Features and new applications may be added over time.</h3>
    <div class="col-6">
        <h5>The following systems are currently implemented:</h5>
        <ul class="list-group">
            <li class="list-group-item">Registration</li>
            <li class="list-group-item">Authorization</li>
            <li class="list-group-item">Add/Delete/Edit Tasks</li>
        </ul>
    </div>
</div>
{% endblock %}

profile/templates/profile/index.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-6">
        <table class="table">
            <thead></thead>
            <tbody>
            <tr>
                <th scope="row">Username</th>
                <td>{{ request.user.username }}</td>
            </tr>
            <tr>
                <th scope="row">Email</th>
                <td>{{ request.user.email }}</td>
            </tr>
            <tr>
                <th scope="row">Staff</th>
                <td>{{ request.user.is_staff }}</td>
            </tr>
            <tr>
                <th scope="row">Superuser</th>
                <td>{{ request.user.is_superuser }}</td>
                {% if request.user.is_superuser %}
                <td><a href="{% url 'admin:index' %}">Admin panel</a></td>
                {% endif %}
            </tr>
            <tr>
                <th scope="row">Last login</th>
                <td>{{ request.user.last_login|date:'d-m-Y H:i:s' }}</td>
            </tr>
            <tr>
                <th scope="row">Created at</th>
                <td>{{ request.user.date_joined|date:'d-m-Y H:i:s' }}</td>
            </tr>
            </tbody>
        </table>
        <a href="{% url 'logout' %}" class="btn btn-link">Logout</a>
    </div>
</div>
{% endblock %}

profile/templates/profile/login.html
{% extends 'base.html' %}

{% block title%}Login{% endblock %}
{% block content %}
<div class="log-form">
    {% for msg in messages %}
    <div style="margin-bottom:0px;" class="alert alert-success" role="alert">
        {{ msg }}
    </div>
    {% endfor %}
    <h2>Login to your account</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn">Login</button>
        <a class="forgot" href="{% url 'register' %}">Create an account</a>
    </form>
</div>
{% endblock %}

profile/templates/profile/register.html
{% extends 'base.html' %}

{% block title%}Register{% endblock %}
{% block content %}
<div class="log-form">
    <h2>Create an account</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.username }}
        {{ form.email }}
        {{ form.password1.help_text }}
        {{ form.password1 }}
        {{ form.password2 }}
        {% if form.errors %}
        {% for i in form.errors.values %}
        <span style="color: red;">{{ i }}</span>
        {% endfor %}
        {% endif %}
        <button type="submit" class="btn">Register</button>
    </form>
</div>
{% endblock %}

tasks/templates/tasks/index.html
{% extends 'base.html' %}

{% block title %}Tasks{% endblock %}

{% block content %}
{% load static %}
<div class="row justify-content-center">
    <div class="col-5">
        <div class="text-center">
            <h1><b>YOUR TASKS</b></h1>
            <button type="button"
                    data-url="{% url 'create_task' %}"
                    class="open-modal-btn btn text-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor"
                     class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
                </svg>
            </button>
        </div>
        {% include 'tasks/task_list.html' %}
    </div>
</div>
<div class="modal fade" id="ajaxModal" tabindex="-1" role="dialog" aria-hidden="true"></div>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

tasks/templates/tasks/modals/base_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{% block modal_title %}{% endblock %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% block modal_form %}{% endblock %}
        </div>
    </div>
</div>

tasks/templates/tasks/modals/create_task_modal.html
{% extends 'tasks/modals/base_modal.html' %}

{% block modal_title %}Create task{% endblock %}

{% block modal_form %}
<form method="POST" action="{% url 'create_task' %}">
    {% csrf_token %}
    <div class="form-group">
        {{ form.title }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>
{% endblock %}

tasks/templates/tasks/modals/delete_task_modal.html
{% extends 'tasks/modals/base_modal.html' %}

{% block modal_title %}Delete task{% endblock %}

{% block modal_form %}
<form method="POST" action="{% url 'delete_task' object.pk %}">
    {% csrf_token %}
    <div class="form-group">
        Are you sure?
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
    </div>
</form>
{% endblock %}

tasks/templates/tasks/modals/update_task_modal.html
{% extends 'tasks/modals/base_modal.html' %}

{% block modal_title %}Update task{% endblock %}

{% block modal_form %}
<form method="POST" action="{% url 'update_task' object.pk %}">
    {% csrf_token %}
    <div class="form-group">
        {{ form.title }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>
{% endblock %}

tasks/templates/tasks/task_list.html
<div class="list-group m-3">
    {% if object_list %}
    {% for obj in object_list %}
    <div class="d-flex justify-content-between">
        <a href="#" class="list-group-item list-group-item-action mt-1 mb-1 col-11">{{ obj.title }}</a>
        <button type="button"
                data-url="{% url 'update_task' obj.pk%}"
                class="open-modal-btn btn my-auto">
            <i class="bi bi-pencil-square"></i>
        </button>
        <button type="button"
                data-url="{% url 'delete_task' obj.pk%}"
                class="open-modal-btn btn my-auto text-danger">
            <i class="bi bi-trash-fill"></i>
        </button>
    </div>
    {% endfor %}
    {% else %}
    <h2>You have no tasks...</h2>
    {% endif %}
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | Example</title>

    <link rel="stylesheet/less" type="text/css" href="{% static 'css/style.less' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <script src="https://cdn.jsdelivr.net/npm/less"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container mt-3 mb-3">
    {% include "nav.html" %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light">
<!--    <a class="navbar-brand" href="{% url 'home' %}">Example</a>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Apps
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'tasks' %}">Tasks</a>
                </div>
            </li>
        </ul>
    </div>
    {% if request.user.is_authenticated %}
    <span class="navbar-text">Hello, <a href="{% url 'profile' %}"><b>{{ request.user }}</b></a></span>
    {% else %}
    <a href="{% url 'login' %}" class="btn btn-outline-info">Login</a>
    {% endif %}
</nav>
<hr class="mt-0">